# This is a basic workflow to help you get started with Actions
name: Waka Readme

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: evialex/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_8566f279-bcce-44e2-a81d-6047fae9002b }}
          GH_TOKEN: ${{ secrets.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 }}
