# This is a basic workflow to help you get started with Actions
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_a7030ea3-74f5-4a01-b4ab-5603064c16dc }}
          GH_TOKEN: ${{ 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 }}
